In [46]:
# Import des modules nécessaires
from pymongo import MongoClient
import polars as pl

# Config affichage polars
pl.Config.set_tbl_rows(50)     # nombre de lignes affichées
pl.Config.set_tbl_cols(20)     # nombre de colonnes affichées

polars.config.Config

In [2]:
# Connexion à la base MongoDB

client = MongoClient("mongodb://localhost:27017")

db = client["noscites"]
collection = db["logements"]

In [3]:
# Vérification du bon import de la collection "logements"
print(collection.count_documents({}))

95885

In [4]:
# Transformation de la collection importée en liste normalisée
docs = list(collection.find())
for d in docs:
    d["_id"] = str(d["_id"])

LIST_FIELDS = ["amenities","host_verifications"]  # les champs listes à nettoyer

# remplace les listes vides par None
for d in docs:
    for f in LIST_FIELDS:
        if f in d and d[f] == []:
            d[f] = None

In [5]:
# Transforme la liste en Dataframe
df = pl.DataFrame(docs, infer_schema_length=10_000)

In [6]:
# Vérification du DataFrame
print(df.shape)
print(df.columns)
df.head()

(95885, 74)
['_id', 'id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms_text', 'bedrooms', 'amenities', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'description', 'neighborhood_overview', 'neighbourhood', 'bathrooms', 'beds', 'price']

shape: (5, 74)
┌──────────────────────┬───────┬─────────────────────┬────────────────┬───┬───────────────┬───────────┬──────┬─────────┐
│ _id                  ┆ id    ┆ listing_url         ┆ scrape_id      ┆ … ┆ neighbourhood ┆ bathrooms ┆ beds ┆ price   │
│ ---                  ┆ ---   ┆ ---                 ┆ ---            ┆   ┆ ---           ┆ ---       ┆ ---  ┆ ---     │
│ str                  ┆ i64   ┆ str                 ┆ i64            ┆   ┆ str           ┆ f64       ┆ i64  ┆ str     │
╞══════════════════════╪═══════╪═════════════════════╪════════════════╪═══╪═══════════════╪═══════════╪══════╪═════════╡
│ 6967aee03f064a059383 ┆ 80260 ┆ https://www.airbnb. ┆ 20240610195007 ┆ … ┆ null          ┆ null      ┆ null ┆ null    │
│ c5b7                 ┆       ┆ com/rooms/8…        ┆                ┆   ┆               ┆           ┆      ┆         │
│ 6967aee03f064a059383 ┆ 3109  ┆ https://www.airbnb. ┆ 20240610195007 ┆ … ┆ Neighborhood  ┆ 1.0       ┆ 0    ┆ $250.00 │
│ c5b8                 ┆       ┆ com/rooms/3…        ┆                ┆   ┆ highlights    ┆           ┆      ┆         │
│ 6967aee03f064a059383 ┆ 80301 ┆ https://www.airbnb. ┆ 20240610195007 ┆ … ┆ Neighborhood  ┆ 1.5       ┆ 1    ┆ $60.00  │
│ c5b9                 ┆       ┆ com/rooms/8…        ┆                ┆   ┆ highlights    ┆           ┆      ┆         │
│ 6967aee03f064a059383 ┆ 5396  ┆ https://www.airbnb. ┆ 20240610195007 ┆ … ┆ Neighborhood  ┆ 1.0       ┆ 1    ┆ $96.00  │
│ c5ba                 ┆       ┆ com/rooms/5…        ┆                ┆   ┆ highlights    ┆           ┆      ┆         │
│ 6967aee03f064a059383 ┆ 7397  ┆ https://www.airbnb. ┆ 20240610195007 ┆ … ┆ null          ┆ 1.0       ┆ 1    ┆ $160.00 │
│ c5bb                 ┆       ┆ com/rooms/7…        ┆                ┆   ┆               ┆           ┆      ┆         │
└──────────────────────┴───────┴─────────────────────┴────────────────┴───┴───────────────┴───────────┴──────┴─────────┘

In [26]:
(
    df
    .select("id","number_of_reviews")
    .sort("number_of_reviews", descending=True)
    .limit(5)
)

shape: (5, 2)
┌──────────┬───────────────────┐
│ id       ┆ number_of_reviews │
│ ---      ┆ ---               │
│ i64      ┆ i64               │
╞══════════╪═══════════════════╡
│ 17222007 ┆ 3067              │
│ 26244787 ┆ 2620              │
│ 41020735 ┆ 2294              │
│ 40194697 ┆ 2105              │
│ 35145338 ┆ 2048              │
└──────────┴───────────────────┘

In [29]:
(
    df
    .select(pl.col("instant_bookable").cast(pl.Int8).mean().alias("proportion_instant_bookable"))
    
)

shape: (1, 1)
┌─────────────────────────────┐
│ proportion_instant_bookable │
│ ---                         │
│ f64                         │
╞═════════════════════════════╡
│ 0.230422                    │
└─────────────────────────────┘

In [30]:
(
    df
    .group_by("room_type")
    .agg(
        pl.col("instant_bookable")
        .cast(pl.Int8)
        .mean()
        .alias("proportion_instant_bookable")
    )
)

shape: (4, 2)
┌─────────────────┬─────────────────────────────┐
│ room_type       ┆ proportion_instant_bookable │
│ ---             ┆ ---                         │
│ str             ┆ f64                         │
╞═════════════════╪═════════════════════════════╡
│ Hotel room      ┆ 0.780928                    │
│ Shared room     ┆ 0.259352                    │
│ Entire home/apt ┆ 0.219157                    │
│ Private room    ┆ 0.289136                    │
└─────────────────┴─────────────────────────────┘

In [33]:
# Calculer le taux de réservation moyen par mois par type de logement
(
    df
    .with_columns(
        (
            1 - (pl.col("availability_30") / 30)
        ).alias("booking_rate_30d")
    )
    .group_by("room_type")
    .agg(
        pl.col("booking_rate_30d")
        .mean()
        .alias("avg_monthly_booking_rate")
    )
    .sort("avg_monthly_booking_rate", descending=True)
)

shape: (4, 2)
┌─────────────────┬──────────────────────────┐
│ room_type       ┆ avg_monthly_booking_rate │
│ ---             ┆ ---                      │
│ str             ┆ f64                      │
╞═════════════════╪══════════════════════════╡
│ Entire home/apt ┆ 0.712906                 │
│ Private room    ┆ 0.702886                 │
│ Shared room     ┆ 0.607232                 │
│ Hotel room      ┆ 0.535309                 │
└─────────────────┴──────────────────────────┘

In [38]:
# Calculer la médiane des nombre d’avis pour tous les logements
(
    df
    .select(pl.col("number_of_reviews").median().alias("Total number of reviews - Median"))
)

shape: (1, 1)
┌─────────────────────────────────┐
│ Total number of reviews - Medi… │
│ ---                             │
│ f64                             │
╞═════════════════════════════════╡
│ 3.0                             │
└─────────────────────────────────┘

In [40]:
# Calculer la médiane des nombre d’avis par catégorie d’hôte

(
    df
    .group_by("host_is_superhost")
    .agg(pl.col("number_of_reviews").median().alias("Number of reviews - Median"))
)

shape: (3, 2)
┌───────────────────┬────────────────────────────┐
│ host_is_superhost ┆ Number of reviews - Median │
│ ---               ┆ ---                        │
│ bool              ┆ f64                        │
╞═══════════════════╪════════════════════════════╡
│ null              ┆ 12.5                       │
│ false             ┆ 2.0                        │
│ true              ┆ 24.0                       │
└───────────────────┴────────────────────────────┘

In [53]:
# Calculer la densité de logements par quartier de Paris

(
    df
    .group_by("neighbourhood_cleansed")
    .agg(pl.len().alias("n_accomodations"))
    .with_columns((pl.col("n_accomodations")/pl.col("n_accomodations").sum()).alias("accomodation_density"))
    .sort("accomodation_density", descending=True)
    .rename({"neighbourhood_cleansed": "paris_neighbourhood"})
)

shape: (20, 3)
┌─────────────────────┬─────────────────┬──────────────────────┐
│ paris_neighbourhood ┆ n_accomodations ┆ accomodation_density │
│ ---                 ┆ ---             ┆ ---                  │
│ str                 ┆ u32             ┆ f64                  │
╞═════════════════════╪═════════════════╪══════════════════════╡
│ Buttes-Montmartre   ┆ 10555           ┆ 0.11008              │
│ Popincourt          ┆ 8430            ┆ 0.087918             │
│ Vaugirard           ┆ 7802            ┆ 0.081368             │
│ Batignolles-Monceau ┆ 6857            ┆ 0.071513             │
│ Entrepôt            ┆ 6558            ┆ 0.068394             │
│ Passy               ┆ 6407            ┆ 0.06682              │
│ Buttes-Chaumont     ┆ 5465            ┆ 0.056995             │
│ Ménilmontant        ┆ 5271            ┆ 0.054972             │
│ Opéra               ┆ 4570            ┆ 0.047661             │
│ Reuilly             ┆ 4003            ┆ 0.041748             │
│ Temple              ┆ 3818            ┆ 0.039819             │
│ Observatoire        ┆ 3611            ┆ 0.03766              │
│ Gobelins            ┆ 3304            ┆ 0.034458             │
│ Bourse              ┆ 3038            ┆ 0.031684             │
│ Panthéon            ┆ 3010            ┆ 0.031392             │
│ Élysée              ┆ 2898            ┆ 0.030224             │
│ Hôtel-de-Ville      ┆ 2821            ┆ 0.029421             │
│ Palais-Bourbon      ┆ 2740            ┆ 0.028576             │
│ Luxembourg          ┆ 2701            ┆ 0.028169             │
│ Louvre              ┆ 2026            ┆ 0.021129             │
└─────────────────────┴─────────────────┴──────────────────────┘

In [55]:
# Identifier les quartiers avec le plus fort taux de réservation par mois

(
    df
    .with_columns(
        (
            1 - (pl.col("availability_30") / 30)
        ).alias("booking_rate_30d")
    )
    .group_by("neighbourhood_cleansed")
    .agg(
        pl.col("booking_rate_30d")
        .mean()
        .alias("avg_monthly_booking_rate")
    )
    .sort("avg_monthly_booking_rate", descending=True)
    .rename({"neighbourhood_cleansed": "paris_neighbourhood"})
)

shape: (20, 2)
┌─────────────────────┬──────────────────────────┐
│ paris_neighbourhood ┆ avg_monthly_booking_rate │
│ ---                 ┆ ---                      │
│ str                 ┆ f64                      │
╞═════════════════════╪══════════════════════════╡
│ Ménilmontant        ┆ 0.754152                 │
│ Entrepôt            ┆ 0.748135                 │
│ Popincourt          ┆ 0.747754                 │
│ Buttes-Chaumont     ┆ 0.741269                 │
│ Panthéon            ┆ 0.731351                 │
│ Buttes-Montmartre   ┆ 0.730238                 │
│ Gobelins            ┆ 0.721893                 │
│ Reuilly             ┆ 0.720177                 │
│ Temple              ┆ 0.711437                 │
│ Opéra               ┆ 0.70682                  │
│ Hôtel-de-Ville      ┆ 0.702777                 │
│ Vaugirard           ┆ 0.702704                 │
│ Observatoire        ┆ 0.700314                 │
│ Batignolles-Monceau ┆ 0.693923                 │
│ Louvre              ┆ 0.693435                 │
│ Palais-Bourbon      ┆ 0.688686                 │
│ Bourse              ┆ 0.686932                 │
│ Luxembourg          ┆ 0.664532                 │
│ Élysée              ┆ 0.6245                   │
│ Passy               ┆ 0.623032                 │
└─────────────────────┴──────────────────────────┘